// app/layout.js
import './globals.css';
import Navbar from './Components/Navbar/Navbar';
import Footer from './Components/Footer/Footer';
import '@fortawesome/fontawesome-free/css/all.min.css';
import BootstrapLoader from './Components/BootstrapLoader/BootstrapLoader';
import Script from 'next/script'; // ✅ Import Next.js Script

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* No need to add Bootstrap CSS here if already imported in globals.css */}
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
        <BootstrapLoader />

        {/* ✅ Correct way to include Bootstrap JS using Next Script */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
